### ISSUE TITLE
Pipeline configuration

### ISSUE THREAD

**Issue by renan601** [fga-eps-mds/2020.1-stay-safe-secretary-service#11]
## Issue Description
Create a new service on docker-compose to run the pipeline. The pipeline should build the project, run the pylint and run tests and generate a response to the user.

## Tasks:
- [x] Add the technologies used in the project.
- [x] Fix pylint errors, if needed.
- [x] Add to docker-compose.
- [x] Update README.md
