### ISSUE TITLE
Refactor DF and SP spiders to catch montly data

### ISSUE THREAD

**Issue by renan601** [fga-eps-mds/2020.1-stay-safe-secretary-service#29]
## Issue Description
Refactor DF and SP spiders to save montly data accordingly with evolved JSON model available at [architecture document](https://fga-eps-mds.github.io/2020.1-stay-safe-docs/projeto/arquitetura/). 

In Crawler DF get the specific crimes available at [architecture document](https://fga-eps-mds.github.io/2020.1-stay-safe-docs/projeto/arquitetura/). Crawler SP is already picking up the right crimes.

Use scrapy function process_spider to save each month (or year) at a time.

Remove gitkeep files in src/utils and src/controllers.

Update controller and swagger according to the above changes, check if the new changes break one of the previous tests and correct if necessary.

## Tasks:
- [x] Refactor DF crawler.
- [x] Refactor SP crawler.
- [x] Save data in MongoDB.
