### ISSUE TITLE
New filters

### ISSUE THREAD

**Issue by silvasara** [fga-eps-mds/2020.1-stay-safe-secretary-service#32]
## Issue Description
Implements filters for cities, for crimes per capita and for months. All filters can be combined. In all filters (existing and new) crimes must be returned in decreasing order of quantities.

### Filter for crimes per capita
In the per_capita filter, the value will be 100,000 inhabitants, and in addition to returning the crime amount / 100k inhabitants, a value between 1 and 6 must be returned, which on the front will represent a color for the heat map. This filter will be a header 'per_capita' in the request.

### Filter for months
It should be possible to pass a range of months, with the initial month being used as the initial_month and the final month as the final_month. Initial_month and final_month should always be used together and the return should be the cumulative amounts of each crime between those months. When inital_month = final_month, only the crime quantities of the month received in the request should be returned.

In this filter, the per capita value must be returned only if the per_capita filter is passed together

### Filter for cities
In this filter, the per capita value must be returned only if the per_capita filter is passed together

### Mongo queries
Current and new filters should use the Mongo's queries when possible.

## Tasks:
- [x] Decide the quantity intervals for each type of crime
- [x] Filter per_capita
- [x] Filter citie
- [x] Filter inital_month and final_month
- [x] Decreasing order of quantities
- [x] Validations
- [x] Update the tests if necessary
- [x] Update swagger
