### ISSUE TITLE
Get SP cities coordinates

### ISSUE THREAD

**Issue by renan601** [fga-eps-mds/2020.1-stay-safe-secretary-service#35]
## Issue Description
Create a new crawler to get a list of coordinates (latitude/longitude pair) for all SP cities. 

Create endpoint get with required state parameter to consume this data.

The list of cities must be taken from [SSP-SP](https://www.ssp.sp.gov.br/estatistica/pesquisa.aspx). The coordinates must be taken from OpenStreetMap API.

Request Example: https://nominatim.openstreetmap.org/search.php?city=Aguaí&state=São+Paulo&country=Brazil&polygon_geojson=1&format=jsonv2

## Additional context
Create a new collection in mongo to save info, the collection must be named coordinates. One document must be made for each state added with all respective cities and coordinates inside.

## JSON format
    {
        "_id": "euh9u",
        "capture_data": "2020-10-20",
        "state": "SP",
        "cities": [
            {
                "name": "Aguaí",
                "coordinates": [
                    [
                        234.234,
                        2343.1232
                    ],
                    [
                        234.234,
                        2343.1232
                    ],
                    [
                        234.234,
                        2343.1232
                    ]
                ]
            }
        ]
    }

## Tasks:
- [x] Create crawler to get all SP cities
- [x] Get coordinates data from each city
- [x] Save in mongoDB in the specified format
- [x] Create endpoints
- [x] Test
