### ISSUE TITLE
Setup production environment

### ISSUE THREAD

**Issue by rossicler** [fga-eps-mds/2020.1-stay-safe-secretary-service#43]
## Issue Description
Create and deploy a production environment.

## Tasks:
- [x] Deploy the api in the machine using apache2
- [x] Run crawlers to get crimes
- [x] Configure crontab to run crime crawlers every month
