### ISSUE TITLE
Improve name of some types of crimes

### ISSUE THREAD

**Issue by silvasara** [fga-eps-mds/2020.1-stay-safe-secretary-service#45]
## Issue Description
In order to improve communication with the user, the need to use more popular names in the types of crimes was raised.
So in the types of "Roubo a Transeunte" and "Furto a Transeunte", changing the word "Transeunte" for "Pedestre".
After this change, it will be necessary to update the tests, filters and corresponding validations.

## Tasks:
- [x] Update the types crimes when the crawlers register on db 
- [x] Update the corresponding filters
- [x] Update the corresponding validations
- [x] Update the conrrespoding tests
- [x] Update the swagger if necessary
